FROM python:3.9-alpine

WORKDIR /usr/src/app
RUN apk add --no-cache --virtual .build-deps gcc musl-dev build-base python3-dev \
     && pip install cython
COPY ./requirements.txt ./
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["flask","run","-h","::","-p","5000"]