FROM python:3.9-alpine

WORKDIR /usr/src/app
RUN apk add --no-cache --virtual .build-deps gcc musl-dev \
     && pip install cython \
     && apk del .build-deps gcc musl-dev
COPY ./requirements.txt ./
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["flask","run"]