version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: contactdb
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin123*
        MYSQL_ROOT_PASSWORD: admin123*
  backend-api:
    image: backend-api
    build:
      context: backend/client_api
    restart: always
    volumes:
      - ./backend/client_api:/usr/src/app
    environment:
      - SECRET_KEY=A0Zr98j/3yX R~XHH!jmN]LWX/,?RT
      - DEBUG=True
      - DATABASE_NAME=contactdb
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin123*
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
    depends_on:
      - db
    ports:
      - "5000:5000"
  client-app:
    image: client-app
    build:
      context: frontend/isucorp
    restart: always
    environment:
      - API_SERVER=backend-api
    depends_on:
      - backend-api
    ports:
      - "80:80"
