"""empty message

Revision ID: 9a4cb86e8049
Revises: 4a7417a69f26
Create Date: 2021-05-04 11:55:26.334738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4cb86e8049'
down_revision = '4a7417a69f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'phone')
    # ### end Alembic commands ###
